web/jdbpj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logetapp.urls')),
]

web/logetapp/urls.py
from django.urls import path
from . import views
from .views import listview, styledetailview, stylemypageview, stylemytestview, storedetailview, dnaapplicationview, itemorderview, dnaapplication_doneview, itemorder_doneview, stylepaperview, stylerepoview, styleadview, stylewebview, storedetailbodyview, skindetailview, skinmypageview, skinmytestview, skinpaperview, skinrepoview, skinadview, skinwebview, storedetailskinview, muscledetailview, musclemypageview, musclemytestview, musclepaperview, musclerepoview, muscleadview, musclewebview, storedetailmuscleview, headdetailview, headmypageview, headmytestview, headpaperview, headrepoview, headadview, headwebview, storedetailheadview, otherdetailview, othermypageview, othermytestview, otherrepoview, otheradview, otherwebview, storedetailotherview, floraexpertdetailview, floraexpertmypageview, floraexpertmytestview, floraexpertrepoview, floraexpertwebview, storedetailfloraexpertview, floralightdetailview, floralightmypageview, floralightmytestview, floralightwebview, storedetailfloralightview, foodproteindetailview, foodproteinmypageview, foodproteinmytestview, foodproteinwebview, storedetailfoodproteinview, skinmyteststoreview, stylemyteststoreview, musclemyteststoreview, headmyteststoreview, floralightmyteststoreview, floraexpertmyteststoreview, foodproteinmyteststoreview, othermyteststoreview, storestylerepoview, storestyleadview, storeskinrepoview, storeskinadview, storemusclerepoview, storemuscleadview, storeheadrepoview, storeheadadview, storefloraexpertrepoview, storeotherrepoview






app_name = 'logetapp'

urlpatterns = [
    path('', views.Login.as_view(), name='index'),
    path('top/', views.Top.as_view(), name='top'),
    path('sample/', views.Sample.as_view(), name='sample'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('list/', listview, name="list"),
    path('styledetail/<int:pk>/', styledetailview, name="styledetail"),
    path('skindetail/<int:pk>/', skindetailview, name="skindetail"),
    path('stylemypage/<int:pk>/', stylemypageview, name="stylemypage"),
    path('skinmypage/<int:pk>/', skinmypageview, name="skinmypage"),
    path('stylemytest/<int:pk>/', stylemytestview, name="stylemytest"),
    path('skinmytest/<int:pk>/', skinmytestview, name="skinmytest"),
    path('skinmyteststore/<int:pk>/', skinmyteststoreview, name="skinmyteststore"),
    path('storedetail/<int:pk>/', storedetailview, name="storedetail"),
    path('dnaapplication/<int:pk>/', dnaapplicationview, name="dnaapplication"),
    path('dnaapplication_done/', dnaapplication_doneview, name="dnaapplication_done"),
    path('itemorder/<int:pk>/', itemorderview, name="itemorder"),
    path('itemorder_done/', itemorder_doneview, name="itemorder_done"),
    path('stylepaper/<int:pk>/', stylepaperview, name="stylepaper"),
    path('stylerepo/<int:pk>/', stylerepoview, name="stylerepo"),
    path('stylead/<int:pk>/', styleadview, name="stylead"),
    path('styleweb/<int:pk>/', stylewebview, name="styleweb"),
    path('storedetail_body/<int:pk>/', storedetailbodyview, name="storedetailbody"),
    path('skindetail/<int:pk>/', skindetailview, name="skindetail"),
    path('skinmypage/<int:pk>/', skinmypageview, name="skinmypage"),
    path('skinpaper/<int:pk>/', skinpaperview, name="skinpaper"),
    path('skinrepo/<int:pk>/', skinrepoview, name="skinrepo"),
    path('skinad/<int:pk>/', skinadview, name="skinad"),
    path('skinweb/<int:pk>/', skinwebview, name="skinweb"),
    path('storedetail_skin/<int:pk>/', storedetailskinview, name="storedetailskin"),
    path('muscledetail/<int:pk>/', muscledetailview, name="muscledetail"),
    path('musclemypage/<int:pk>/', musclemypageview, name="musclemypage"),
    path('musclepaper/<int:pk>/', musclepaperview, name="musclepaper"),
    path('musclerepo/<int:pk>/', musclerepoview, name="musclerepo"),
    path('musclead/<int:pk>/', muscleadview, name="musclead"),
    path('muscleweb/<int:pk>/', musclewebview, name="muscleweb"),
    path('musclemytest/<int:pk>/', musclemytestview, name="musclemytest"),
    path('storedetail_muscle/<int:pk>/', storedetailmuscleview, name="storedetailmuscle"),
    path('headdetail/<int:pk>/', headdetailview, name="headdetail"),
    path('headmypage/<int:pk>/', headmypageview, name="headmypage"),
    path('headpaper/<int:pk>/', headpaperview, name="headpaper"),
    path('headrepo/<int:pk>/', headrepoview, name="headrepo"),
    path('headad/<int:pk>/', headadview, name="headad"),
    path('headweb/<int:pk>/', headwebview, name="headweb"),
    path('headmytest/<int:pk>/', headmytestview, name="headmytest"),
    path('storedetail_head/<int:pk>/', storedetailheadview, name="storedetailhead"),
    path('floralightdetail/<int:pk>/', floralightdetailview, name="floralightdetail"),
    path('floralightmypage/<int:pk>/', floralightmypageview, name="floralightmypage"),
    path('floralightweb/<int:pk>/', floralightwebview, name="floralightweb"),
    path('floralightmytest/<int:pk>/', floralightmytestview, name="floralightmytest"),
    path('storedetail_floralight/<int:pk>/', storedetailfloralightview, name="storedetailfloralight"),
    path('floraexpertdetail/<int:pk>/', floraexpertdetailview, name="floraexpertdetail"),
    path('floraexpertmypage/<int:pk>/', floraexpertmypageview, name="floraexpertmypage"),
    path('floraexpertrepo/<int:pk>/', floraexpertrepoview, name="floraexpertrepo"),
    path('floraexpertweb/<int:pk>/', floraexpertwebview, name="floraexpertweb"),
    path('floraexpertmytest/<int:pk>/', floraexpertmytestview, name="floraexpertmytest"),
    path('storedetail_floraexpert/<int:pk>/', storedetailfloraexpertview, name="storedetailfloraexpert"),
    path('foodproteindetail/<int:pk>/', foodproteindetailview, name="foodproteindetail"),
    path('foodproteinmypage/<int:pk>/', foodproteinmypageview, name="foodproteinmypage"),
    path('foodproteinweb/<int:pk>/', foodproteinwebview, name="foodproteinweb"),
    path('foodproteinmytest/<int:pk>/', foodproteinmytestview, name="foodproteinmytest"),
    path('storedetail_foodprotein/<int:pk>/', storedetailfoodproteinview, name="storedetailfoodprotein"),
    path('otherdetail/<int:pk>/', otherdetailview, name="otherdetail"),
    path('othermypage/<int:pk>/', othermypageview, name="othermypage"),
    path('otherrepo/<int:pk>/', otherrepoview, name="otherrepo"),
    path('otherad/<int:pk>/', otheradview, name="otherad"),
    path('otherweb/<int:pk>/', otherwebview, name="otherweb"),
    path('othermytest/<int:pk>/', othermytestview, name="othermytest"),
    path('storedetail_other/<int:pk>/', storedetailotherview, name="storedetailother"),
    path('stylemyteststore/<int:pk>/', stylemyteststoreview, name="stylemyteststore"),
    path('musclemyteststore/<int:pk>/', musclemyteststoreview, name="musclemyteststore"),
    path('headmyteststore/<int:pk>/', headmyteststoreview, name="headmyteststore"),
    path('floralightmyteststore/<int:pk>/', floralightmyteststoreview, name="floralightmyteststore"),
    path('floraexpertmyteststore/<int:pk>/', floraexpertmyteststoreview, name="floraexpertmyteststore"),
    path('foodproteinmyteststore/<int:pk>/', foodproteinmyteststoreview, name="foodproteinmyteststore"),
    path('othermyteststore/<int:pk>/', othermyteststoreview, name="othermyteststore"),
    path('storestylerepo/<int:pk>/', storestylerepoview, name="storestylerepo"),
    path('storestylead/<int:pk>/', storestyleadview, name="storestylead"),
    path('storeskinrepo/<int:pk>/', storeskinrepoview, name="storeskinrepo"),
    path('storeskinad/<int:pk>/', storeskinadview, name="storeskinad"),
    path('storemusclerepo/<int:pk>/', storemusclerepoview, name="storemusclerepo"),
    path('storemusclead/<int:pk>/', storemuscleadview, name="storemusclead"),
    path('storeheadrepo/<int:pk>/', storeheadrepoview, name="storeheadrepo"),
    path('storeheadad/<int:pk>/', storeheadadview, name="storeheadad"),
    path('storefloraexpertrepo/<int:pk>/', storefloraexpertrepoview, name="storefloraexpert"),
    path('storeotherrepo/<int:pk>/', storeotherrepoview, name="storeotherrepo"),
]

web/logetapp/templates/register/base_store.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

    <title>JDB遺伝子検査</title>
    {% block header %}{% endblock %}
</head>
<body>

<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark indigo">
    <a class="navbar-brand" href="#"><strong>JDB遺伝子検査</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logetapp:top' %}">マイページ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logetapp:logout' %}">ログアウト</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logetapp:storedetail' user.pk %}">店舗ページ</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logetapp:login' %}">新規登録・ログインはこちら</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </nav>

</header>

    <!-- メインコンテント -->
    <div class="container mt-3" style="padding-top:50px;">
    <p><center><img src="{% static 'images/logo_ecrin.png' %}" style="max-width:100%;"></center></p>
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

web/logetapp/templates/register/base_web.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

    <title>JDB遺伝子検査</title>
    {% block header %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
   <!-- footer
   ================================================== -->
   <footer>
      <div class="row">
         <div class="twelve columns">
            <ul class="copyright">
               <li>&copy; Copyright 2020 JDB遺伝子検査</li>
            </ul>
         </div>
         <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#home"><i class="icon-up-open"></i></a></div>
      </div>
   </footer> <!-- Footer End-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

web/logetapp/templates/register/email_change_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    確認メールに記載されているリンクをクリックすると、アドレスが変更されます。
</p>
{% endblock %}

web/logetapp/templates/register/foodproteinmypage.html
{% extends "register/base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}

{% block content %}
<div class="container">
    <h1>SkinDNA</h1>

    <p>検体IDと検体パスワードを入力してください。</p>

    {% if object.skinansno == None %}
    <form action="{% url 'logetapp:skinmypage' object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <tr><td></td><td><input type="submit" value="取得"></td></tr>
    </form>
    {% endif %}

</div>


{% endblock %}

web/logetapp/templates/register/getmiss.html
{% extends "register/base.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<p>
    検体IDもしくは検体パスワードが間違っています。<br>
    <a href="{% url 'logetapp:top' %}">マイページへ戻る。</a>
</p>
{% endblock %}

web/logetapp/templates/register/logout.html
{% extends "register/base_no_message.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<p>
    ログアウトが完了しました。<br>
    ログイン・新規登録は<a href="{% url 'logetapp:login' %}">こちら</a>からお願いします。
</p>
{% endblock %}

web/logetapp/templates/register/otherdetail.html
{% extends "register/base.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-6 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal" style="font-size:150%; padding:1em;">その他の検査</h4>
      </div>
      <div class="card-body">
        <form action="{% url 'logetapp:othermypage' object.pk %}" method="POST">
            {% csrf_token %}
            <table class="table" style="width:50%; margin:2em auto;">
            {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary" style="width:50%; margin:auto;">結果を取得</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

web/logetapp/templates/register/othermypage.html
{% extends "register/base.html" %}
{% load static %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}

{% block content %}
<div class="container">
    <h1>SkinDNA</h1>

    <p>検体IDと検体パスワードを入力してください。</p>

    {% if object.skinansno == None %}
    <form action="{% url 'logetapp:skinmypage' object.pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <tr><td></td><td><input type="submit" value="取得"></td></tr>
    </form>
    {% endif %}

</div>


{% endblock %}

web/logetapp/templates/register/password_change.html
{% extends "register/base.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

web/logetapp/templates/register/storedetail_floraexpert.html
{% extends "register/base_store.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <p><center><img src="{% static 'images/h_expert_logo.png' %}" style="max-width:100%;"></center></p>

    <table class="table table-bordered" style="margin:auto;">
{% for item in targetfloraexpert reversed %}
    <tbody>
    <tr align="center">
        <th><button type="button" class="btn btn-link"><b>{{ item.floraexpertname }}</b></button></th>
        <td>
            <a href="{% url 'logetapp:floraexpertmyteststore' item.pk %}"><button type="button" class="btn btn-outline-danger" style="width:11em; padding:1em;">webページ</button></a>
            <a href="{% url 'logetapp:storefloraexpertrepo' item.pk %}"><button type="button" class="btn btn-outline-warning" style="width:11em; padding:1em;">レポートブック</button></a>
            <a href="{% url 'logetapp:storefloraexpertad' item.pk %}"><button type="button" class="btn btn-outline-success" style="width:11em; padding:1em;">アドバイスブック</button></a>
            <a href="{% url 'logetapp:floraexpertweb' item.pk %}"><button type="button" class="btn btn-outline-primary" style="width:11em; padding:1em;">ログイン用紙</button></a>
            <a href="{% url 'logetapp:floraexpertpaper' item.pk %}"><button type="button" class="btn btn-outline-secondary" style="width:11em; padding:1em;">カンペ</button></a>
        </td>
    </tr>
    </tbody>
{% endfor %}

    </table>
<p><center><a href="{% url 'logetapp:storedetail' user.pk  %}">一覧へ戻る</a></center></p>
</div>
{% endblock %}

web/logetapp/templates/register/storedetail_foodprotein.html
{% extends "register/base_store.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <p><center><img src="{% static 'images/h_protein_logo.png' %}" style="max-width:100%;"></center></p>

    <table class="table table-bordered" style="margin:auto;">
{% for item in targetfoodprotein reversed %}
    <tbody>
    <tr align="center">
        <th><button type="button" class="btn btn-link"><b>{{ item.foodproteinname }}</b></button></th>
        <td>
            <a href="{% url 'logetapp:foodproteinmyteststore' item.pk %}"><button type="button" class="btn btn-outline-danger" style="width:11em; padding:1em;">webページ</button></a>
            <a href="{% url 'logetapp:foodproteinrepo' item.pk %}"><button type="button" class="btn btn-outline-warning" style="width:11em; padding:1em;">レポートブック</button></a>
            <a href="{% url 'logetapp:foodproteinad' item.pk %}"><button type="button" class="btn btn-outline-success" style="width:11em; padding:1em;">アドバイスブック</button></a>
            <a href="{% url 'logetapp:foodproteinweb' item.pk %}"><button type="button" class="btn btn-outline-primary" style="width:11em; padding:1em;">ログイン用紙</button></a>
            <a href="{% url 'logetapp:foodproteinpaper' item.pk %}"><button type="button" class="btn btn-outline-secondary" style="width:11em; padding:1em;">カンペ</button></a>
        </td>
    </tr>
    </tbody>
{% endfor %}

    </table>
<p><center><a href="{% url 'logetapp:storedetail' user.pk  %}">一覧へ戻る</a></center></p>
</div>
{% endblock %}

web/logetapp/templates/register/styledetail.html
{% extends "register/base_no_message.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-6 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal" style="font-size:150%; padding:1em;">diet&bodymake JDB</h4>
      </div>
      <div class="card-body">
        <form action="{% url 'logetapp:stylemypage' object.pk %}" method="POST">
            {% csrf_token %}
            <table class="table" style="width:50%; margin:2em auto;">
            {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-lg btn-block btn-outline-primary" style="width:50%; margin:auto;">結果を取得</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

web/logetapp/templates/register/user_create.html
{% extends "register/base_no_message.html" %}
{% load static %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mdb.css' %}">
{% endblock %}

{% block content %}
<div style="width:80%; margin-left:auto; margin-right:auto;">
    <button class="btn btn-outline-primary" style="width:100%; font-size:150%; margin-bottom:1em;">新規登録</button>
    以下にメールアドレスと任意のパスワード（8文字以上、数字のみは不可）を入力してください。
    <hr>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <center><button type="submit" class="btn btn-primary btn-lg">送信</button></center>
</form>
送信後、すぐに登録完了となりますので、メールアドレスとパスワードをご確認の上送信ボタンを押してください。
</div>
{% endblock %}